modLoader = "javafml"
loaderVersion = "[1,)"

license = "UNLICENSED"

[[mods]]
modId = "damagenumbers"
version = "${version}"

displayName = "Damage Numbers"
displayURL = "https://modrinth.com/project/damagenumbers"

logoFile = "assets/damagenumbers/icon.png"

authors = "luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Adds simple damage number particles when any entity takes damage."

[[mixins]]
config = "damagenumbers.mixins.json"

[[dependencies.damagenumbers]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.damagenumbers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
